Off campus user
faustino99/DartMate pull request #34
Opened 2021-03-08 03:15 UTC by faustino99

- Off campus user profiles show city location instead of housing community
- Made a lot of minor styling changes to the profile page so it is much more width responsive

2021-03-08 17:51 UTC, hpfoster9 requested changes

2021-03-08 17:51 UTC, hpfoster9 commented on src/components/Feed.js
> +      <div className="profile-container" onClick={() => this.props.goToProfile(this.props.history, i)} key={i}>
the goToProfile function has changed to take a callback function to return to the parent screen.

2021-03-08 17:51 UTC, hpfoster9 commented on src/components/ProfilePage.js
> +              { this.props.showOther && <img className="back-arrow" src={Back} alt="Back" onClick={() => this.props.history.push('/feed')} /> }
Same as prior comment, the goToProfile works differently now because you can go to the profile from the match page so this needs to be more dynamic

2021-03-09 00:38 UTC, faustino99 commented on src/components/ProfilePage.js
> +              { this.props.showOther && <img className="back-arrow" src={Back} alt="Back" onClick={() => this.props.history.push('/feed')} /> }
lets merge your PR first, then I can add that change when i merge the main branch into this branch

2021-03-09 00:54 UTC, hpfoster9 commented on src/components/ProfilePage.js
> +              { this.props.showOther && <img className="back-arrow" src={Back} alt="Back" onClick={() => this.props.history.push('/feed')} /> }
Sounds, will approve

2021-03-09 00:54 UTC, hpfoster9 approved these changes

2021-03-09 03:31 UTC, merged